#pragma once

typedef enum {
    AST_UNKNOWN_NODE,
    /* MISC */
    AST_FUNCSIGN_NODE,
    AST_ARGDEF_NODE,
    AST_IDENTIFIER_NODE,
    /* MODULE ITEM */
    AST_FUNCDEF_NODE,
    /* TYPEREF */
    AST_BUILTIN_TYPEREF_NODE,
    AST_CUSTOM_TYPEREF_NODE,
    AST_ARRAY_TYPEREF_NODE,
    /* STATEMENT */
    AST_VARDECL_STMT_NODE,
    AST_CONDITION_STMT_NODE,
    AST_WHILE_STMT_NODE,
    AST_DO_WHILE_STMT_NODE,
    AST_BREAK_STMT_NODE,
    AST_CONTINUE_STMT_NODE,
    AST_EXPRESSION_STMT_NODE,
    AST_RETURN_STMT_NODE,
    /* EXPRESSION */
    AST_BINARY_EXPR_NODE,
    AST_UNARY_EXPR_NODE,
    AST_BRACES_EXPR_NODE,
    AST_CALL_OR_INDEXER_EXPR_NODE,
    AST_PLACE_EXPR_NODE,
    AST_TERNARY_EXPR_NODE,
    /* LITERALS */
    AST_STRING_LITERAL_NODE,
    AST_CHAR_LITERAL_NODE,
    AST_DEC_LITERAL_NODE,
    AST_HEX_LITERAL_NODE,
    AST_OCT_LITERAL_NODE,
    AST_BITS_LITERAL_NODE,
    AST_BOOL_LITERAL_NODE,
} ASTNodeKind;